###Registraton
POST http://localhost:3000/api/user/register
Content-Type: application/json

{
    "name": "Bartek Áron",
    "email": "bartekaron@gmail.com",
    "password": "Anyabiztosszeret123"
    
}

###Login
POST http://localhost:3000/api/user/login
Content-Type: application/json

{
    "email": "csanikevin@gmail.com",
    "password": "Tarrmaci01"
    
}
